### ISSUE TITLE
fibers@2.0.0 install: `node build.js || nodejs build.js` npm ERR! Exit status 134 npm ERR! npm ERR! Failed at the fibers@2.0.0 install script 'node build.js || nodejs build.js'.

### ISSUE THREAD

**Issue by czhao028** [laverdet/node-fibers#358] opened 2018-01-18 02:29 UTC
I have the latest node.js installed, but whenever I do "npm install sync", which has a dependency on this, it returns this error. Here is debug.log - 
[npm-debug.log](https://github.com/laverdet/node-fibers/files/1641386/npm-debug.log)

**Comment by bjankord** [comment] 2018-01-18 02:50
I just noticed similar errors in my jenkins build. After running npm install, it errors out

Here's a bit of the error log

```
npm ERR! prepareGitDep 1> 
npm ERR! prepareGitDep > fibers@2.0.0 install /home/ph/.npm/_cacache/tmp/git-clone-479434ae/node_modules/fibers
npm ERR! prepareGitDep > node build.js || nodejs build.js
npm ERR! prepareGitDep 
npm ERR! prepareGitDep `linux-x64-57` exists; testing
```

What's odd to me is it doesn't look like there have been in new releases of this project.
Last release looks like it was 7 months ago.

<img width="374" alt="screen shot 2018-01-17 at 8 48 37 pm" src="https://user-images.githubusercontent.com/633148/35078436-e465dff6-fbc7-11e7-9f3d-b4388872067a.png">

I'm not using fibers directly, its a transitive dependency to one that I'm using, not sure which one yet. Though seeing as how this project hasn't been released in 7 months, it makes me wonder if one of this projects dependencies is actually causing the error.

**Comment by benjamn** [comment] 2018-01-18 02:59
What happens if you install another binary npm package, such as `bcrypt`? If that fails too, you may need to run through the setup instructions for `node-gyp`, which is responsible for compiling most binary npm packages: https://github.com/nodejs/node-gyp/#installation

**Comment by bjankord** [comment] 2018-01-18 03:38
I'm unable to reproduce the error at this time. ¯\_(ツ)_/¯
If I see this issue again, I'll post back here.

**Comment by czhao028** [comment] 2018-01-18 04:58
npm install bcrypt --build-from-source works, but thank you for your help, it turned out just to be a memory error! My school allocates certain amounts of memory to each user in the web portal we use to build apps and the issue was resolved by allocating my account more space.

**Comment by cuongluu8** [comment] 2018-02-08 09:39
@bjankord I think I'm currently experiencing this issue - like you it's failing in my jenkins build and like you I am also using `wdio-sync`.  Do you remember what you did to resolve this?

Looking at my logs it looks like it pickup up an incorrect version of `node-gyp`
```
/var/lib/jenkins/.node-gyp/0.12.0/src/node.h: In function ‘void node::FatalException(const v8::TryCatch&)’:
```
I am using node 6 (through nvm), so I assume it should be picking it node-gyp from there.

**Comment by bjankord** [comment] 2018-02-08 13:13
@cuongluu8 Ah thats interesting about using node 6. Our jenkins executors did not have the same version of node consistently among them. Most where on node 8 and one was on node 6. Our build would run on whichever executor was available and we were not controlling the node version via nvm like we should have. I believe we hit this issue likely when the build was running on a jenkins executor with node 6 and "resolved" itself when the build ran on another executor that had node 8.

**Comment by saintx** [comment] 2018-03-25 05:34
I was able to solve this problem tonight by upgrading to the latest stable version of node.

**Comment by cuongluu8** [comment] 2018-03-26 07:53
this ended up being caused by a separate problem.  Basically because our production environment was still running Node 0.12, our pipeline does a `npm rebuild` using node 0.12.  The problem with this is that `npm rebuild` builds ALL dependencies, including dev dependencies, which is where this error is coming from (for me anyway).
Therefore we had to do a `npm prune --production` to remove all dev dependencies before `npm rebuild`

**Closed** 2018-04-16 20:43 UTC
