### ISSUE TITLE
Unable to build on travis-ci.com / node 6.5.0

### ISSUE THREAD

**Issue by lcalvy** [laverdet/node-fibers#306] opened 2016-09-02 07:54 UTC
Hi,

We have issue with fibers package installed on travis-ci.com.
Node 6.5.0
NPM 3.10.3

```
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.5.0/bin/node" "/home/travis/.nvm/versions/node/v6.5.0/bin/npm" "install"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.13 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@1.0.13 install script 'node build.js || nodejs build.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fibers
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fibers
```

.travis.yml
```YAML
language: node_js
node_js:
- 6.5.0
sudo: false
cache:
  directories:
  - node_modules
install:
- npm install
script:
- npm test
````

Fibers is a dependency of another module
```
Cockpit@2.5.1 
└─┬ wdio-mocha-framework@0.4.0
  └─┬ wdio-sync@0.5.10
    └── fibers@1.0.13 
```

**Comment by sjmcdowall** [comment] 2016-09-02 14:37
This seems a duplicate of #304 ??  (closed issue)

**Comment by shri3k** [comment] 2016-09-02 23:03
What's weird is that in `npmjs.org` it's showing that `1.0.14` is the latest version while I just see `1.0.13` as the latest release from the github profile.

**Comment by laverdet** [comment] 2016-09-03 09:06
Use `1.0.14`. There are no code updates but it has binaries for 6.5.0.

**Closed by laverdet** 2016-09-03 09:06 UTC

**Comment by AlexandreBonneau** [comment] 2017-01-23 19:39
Apparently the build problem still exists with 1.0.15 (see the build log [here](https://travis-ci.org/BobKnothe/autoNumeric/builds/194579002) (line 246).

**Comment by AlexandreBonneau** [comment] 2017-04-04 03:42
Is it possible to re-open this issue since the problem seems to have not been fixed in 1.0.15?

**Comment by AlexandreBonneau** [comment] 2018-01-31 06:42
Pretty please? 😜

**Comment by laverdet** [comment] 2018-01-31 18:57
@AlexandreBonneau your problem is that you're using node v7.x. I don't supply binary releases for odd-numbered versions of nodejs. If you upgrade to node v8.x this will work just fine.

Alternatively you can add the relevant bits of my [.travis.yml](https://github.com/laverdet/node-fibers/blob/master/.travis.yml) to your project to get a compatible compiler installed before running your CI.

**Comment by AlexandreBonneau** [comment] 2018-01-31 19:02
I'll try, thanks!
